feat: Redis made optional
noodle-run/noodle pull request #333
Opened 2023-10-28 22:28 UTC by YoussefLaunchUp

I made a small change to make Redis (and rate limiting) optional, this is to make local development easier. I updated the contributing doc to reflect this as well. Just leaving the UPSTASH_REDIS_REST_URL empty will lead to skipping rate limiting.

2023-10-31 21:55 UTC, ixahmedxi requested changes

2023-10-31 21:55 UTC, ixahmedxi commented on package.json
> +    "scheduler": ">=0.19.0",
you haven't required any new packages so please revert the changes to package.json and pnpm-lock.yaml files

2023-10-31 21:55 UTC, ixahmedxi commented on .devcontainer/devcontainer.json
> +	"name": "Node.js & TypeScript",
this file is outside of the scope of the pr and should be removed

2023-10-31 21:55 UTC, ixahmedxi commented on .codesandbox/tasks.json
> +  "setupTasks": [
this file is outside the scope of the PR and should be removed

2023-10-31 22:29 UTC, YoussefLaunchUp commented
@ixahmedxi removed the newer commites

2023-11-01 06:35 UTC, Erb3 commented on CONTRIBUTING.md
> +9. Upstash is only used for ratelimiting, if left empty then ratelimiting will be disabled
I feel this looks like a step of setting up upstash, since it is in the ordered list. I would probably place it above the ordered list so that people read it before setting up upstash.

2023-11-01 17:30 UTC, ixahmedxi requested changes

2023-11-01 17:30 UTC, ixahmedxi commented on CONTRIBUTING.md
> +9. Upstash is only used for ratelimiting, if left empty then ratelimiting will be disabled
Replace this line with the current content and place it on top of the bullet list, as a note when the user firstly starts reading this section:

```markdown
> **Note** Upstash is used to provide rate-limiting capabilities to Noodle, which is optional when self hosting as that it's really only needed in the production version.
```

2023-11-03 22:52 UTC, merged